"""
Runtime loader for the curated Synthea patients.

This is what FastAPI imports at startup. It reads the slim JSON
generated by ``curate.py`` and exposes it as a list of
``PatientSummary`` dictionaries. If the file is missing it returns an
empty list so the engine still starts cleanly — the /demo endpoint will
just return an empty array and the UI will hide the picker.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

_DEFAULT_PATH = Path(__file__).parent / "sample_patients" / "patients.json"

# Synthea generates verbose RxNorm-style medication labels like
# "24 HR metoprolol succinate 100 MG Extended Release Oral Tablet". The
# /triage UI and the /pharmacy/search BFF want the bare ingredient
# ("metoprolol"), so we strip dosage / formulation tokens at load time.
# Keeping the raw strings in patients.json preserves provenance.
# Iteratively strip nested () [] {} groups so combo packs collapse,
# then nuke dosages, units, and formulation/salt words.
_BRACKET_PATTERNS = (
    re.compile(r"\{[^{}]*\}"),
    re.compile(r"\[[^\[\]]*\]"),
    re.compile(r"\([^()]*\)"),
)
_DOSAGE_UNIT_PATTERN = re.compile(
    r"\b\d+(?:\.\d+)?\s*(?:hr|hour|hours|mg|mcg|ml|g|iu|actuat)\b",
    re.IGNORECASE,
)
_BARE_NUMBER_PATTERN = re.compile(r"\b\d+(?:\.\d+)?\b")
_UNIT_AFTER_SLASH_PATTERN = re.compile(r"/\s*(?:actuat|ml|mg|mcg|iu|hr)\b", re.IGNORECASE)
_FORMULATION_PATTERN = re.compile(
    r"\b("
    r"oral|tablet|tablets|capsule|capsules|chewable|extended|release|"
    r"injection|injectable|suspension|spray|mucosal|nasal|topical|"
    r"solution|patch|cream|ointment|drops|prefilled|syringe|inhaler|"
    r"inhalation|pack|actuat|metered|dose|hcl|sodium|chloride|sulfate|"
    r"succinate|hydrochloride|maleate|tartrate|fumarate|inert|ingredients"
    r")\b",
    re.IGNORECASE,
)
_BRAND_DAY_TAIL = re.compile(r"\s+\d+\s*day\b.*$", re.IGNORECASE)


_BRAND_HINT = re.compile(r"\[([^\[\]]+)\]")


def _clean_med(name: str) -> str:
    # If the raw FHIR string ends with a brand bracket like
    # "... Pack [Trinessa 28 Day]", remember it as a fallback in case
    # cleaning the technical noise leaves us with nothing usable.
    brand_hint: str = ""
    brand_match = _BRAND_HINT.findall(name)
    if brand_match:
        candidate = brand_match[-1].strip()
        candidate = _BRAND_DAY_TAIL.sub("", candidate).strip()
        if candidate:
            brand_hint = candidate

    cleaned = name
    # Iteratively peel nested groups until stable.
    for _ in range(5):
        before = cleaned
        for pat in _BRACKET_PATTERNS:
            cleaned = pat.sub(" ", cleaned)
        if cleaned == before:
            break
    cleaned = _DOSAGE_UNIT_PATTERN.sub(" ", cleaned)
    cleaned = _UNIT_AFTER_SLASH_PATTERN.sub(" ", cleaned)
    cleaned = _BARE_NUMBER_PATTERN.sub(" ", cleaned)
    cleaned = _FORMULATION_PATTERN.sub(" ", cleaned)
    cleaned = _BRAND_DAY_TAIL.sub("", cleaned)
    cleaned = re.sub(r"\s*/\s*", " / ", cleaned)
    cleaned = re.sub(r"(?:\s*/\s*){2,}", " / ", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip(" ,;:.-/")
    if cleaned:
        return cleaned
    if brand_hint:
        return brand_hint
    return name


@dataclass
class PatientSummary:
    id: str
    label: str
    bucket: str
    age: int
    sex: str
    postal_code: str
    city: str
    state: str
    active_conditions: List[str]
    active_medications: List[str]
    allergies: List[str]
    last_vitals: Dict[str, Any]
    narrative_seed: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "label": self.label,
            "bucket": self.bucket,
            "age": self.age,
            "sex": self.sex,
            "postal_code": self.postal_code,
            "city": self.city,
            "state": self.state,
            "active_conditions": self.active_conditions,
            "active_medications": self.active_medications,
            "allergies": self.allergies,
            "last_vitals": self.last_vitals,
            "narrative_seed": self.narrative_seed,
        }


_CACHE: Optional[List[PatientSummary]] = None


def _load_from_disk(path: Path = _DEFAULT_PATH) -> List[PatientSummary]:
    if not path.exists():
        return []
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    out: List[PatientSummary] = []
    for entry in raw.get("patients") or []:
        try:
            out.append(PatientSummary(
                id=str(entry["id"]),
                label=str(entry.get("label", entry["id"])),
                bucket=str(entry.get("bucket", "unbucketed")),
                age=int(entry.get("age", 0)),
                sex=str(entry.get("sex", "unknown")),
                postal_code=str(entry.get("postal_code", "")),
                city=str(entry.get("city", "")),
                state=str(entry.get("state", "")),
                active_conditions=list(entry.get("active_conditions") or []),
                active_medications=[
                    _clean_med(m) for m in (entry.get("active_medications") or [])
                ],
                allergies=list(entry.get("allergies") or []),
                last_vitals=dict(entry.get("last_vitals") or {}),
                narrative_seed=str(entry.get("narrative_seed", "")),
            ))
        except (KeyError, TypeError, ValueError):
            continue
    return out


def load_demo_patients(*, force_reload: bool = False) -> List[PatientSummary]:
    """Return the curated demo patients, caching the parse for the
    process lifetime."""
    global _CACHE
    if _CACHE is None or force_reload:
        _CACHE = _load_from_disk()
    return _CACHE


def list_demo_patients() -> List[Dict[str, Any]]:
    """JSON-ready list of demo patients for the /demo endpoint."""
    return [p.to_dict() for p in load_demo_patients()]
