import { NextResponse } from 'next/server';
import { recordTier } from '@/lib/ai-telemetry';

/**
 * Proxy to the FastAPI AI engine for patient intake analysis.
 *
 * Resilience layers:
 *   1. FastAPI service itself runs a Tier 0→1→2→3 cascade — if Gemini is
 *      down, FastAPI still returns a grounded or safe response.
 *   2. If FastAPI is itself unreachable, this route degrades to a minimal
 *      Tier-3 response so the patient experience never breaks.
 *   3. Every successful response's `source_tier` is recorded to telemetry
 *      so the ops dashboard can show live AI reliability numbers.
 */
export async function POST(req: Request) {
  const body = (await req.json().catch(() => ({}))) as Record<string, unknown>;

  // Defense in depth: FastAPI's IntakeRequest expects `severity` as a string.
  // The /triage page sends a numeric NRS score (e.g. 7), so coerce here so the
  // request can never trip Pydantic validation regardless of caller shape.
  const normalizedBody: Record<string, unknown> = { ...body };
  if (typeof normalizedBody.severity === 'number') {
    const n = normalizedBody.severity as number;
    normalizedBody.severity = n >= 7 ? 'severe' : n >= 4 ? 'moderate' : 'mild';
  } else if (normalizedBody.severity == null) {
    normalizedBody.severity = 'moderate';
  } else {
    normalizedBody.severity = String(normalizedBody.severity);
  }

  const aiEngineUrl = process.env.AI_ENGINE_URL || 'http://localhost:8001/analyze-intake';

  try {
    const response = await fetch(aiEngineUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-internal-secret': process.env.INTERNAL_API_SECRET ?? 'frudgecare-internal-dev-secret',
      },
      body: JSON.stringify(normalizedBody),
    });

    if (!response.ok) {
      throw new Error(`AI engine returned ${response.status}`);
    }

    const result = await response.json();
    recordTier('analyze-intake', result?.source_tier);
    return NextResponse.json(result);
  } catch (error) {
    console.error('AI Integration Error — falling back to Next.js local Tier 3:', error);

    // `normalizedBody.severity` is guaranteed to be a string at this point,
    // but we still guard with String(...) so this fallback is bullet-proof
    // for any future caller shape.
    const severityStr = String(normalizedBody.severity ?? '').toLowerCase();
    const urgency = severityStr.includes('severe')
      ? 'high'
      : severityStr.includes('moderate')
      ? 'medium'
      : 'low';

    const symptoms = String(normalizedBody.symptoms ?? '').slice(0, 240);

    const fallback = {
      urgency,
      summary:
        "Your symptoms have been logged. A clinician will review your case shortly.",
      risks: [] as string[],
      reasoning:
        "AI engine unreachable from web tier; applying safe severity-based default. Nurse will validate.",
      clinician_brief: `Patient reports: ${symptoms}. Clinical review required — AI engine unavailable.`,
      source_tier: 3,
      provenance: [] as string[],
      // Hackathon-extension defaults so the /triage UI still renders fully.
      urgency_reason:
        "AI engine unreachable. Using a safe severity-based default — a clinician must review.",
      extracted_symptoms: [] as string[],
      negations: [] as string[],
      rag_evidence:
        "Engine offline — no clinical guideline retrieval performed for this request.",
      rag_source: "Web tier fallback (no retrieval available)",
      recommended_route:
        urgency === 'high'
          ? "Emergency Department — escalate to senior clinician now"
          : urgency === 'medium'
          ? "Same-day clinic visit — primary care or urgent care"
          : "Primary care follow-up — non-time-critical",
      fhir_output: {
        resourceType: "CarePlan",
        status: "active",
        intent: "plan",
        title: "Triage Care Plan (offline fallback)",
        description: "Generated by web tier when AI engine was unreachable.",
      },
    };
    recordTier('analyze-intake', 3);
    return NextResponse.json(fallback);
  }
}
